-- Generated by nwg-displays on 2026-09-25 at 13:37:05. Do not edit manually.

hl.monitor({
    output = "DP-2",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "0x0@60.0",
    position = "-1x-1",
    scale = 1,
    vrr = 0
})
