-- Generated by nwg-displays on 2026-09-07 at 22:02:56. Do not edit manually.

hl.monitor({
    output = "DP-2",
    disabled = true
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "-1x-1",
    scale = 1.0
})
