-- Generated by nwg-displays on 2026-09-05 at 16:59:54. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "HDMI-A-1"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "DP-2",
    default = true
})
